---
title: ""
output: html_document
date: "`r format(Sys.time(), '%d %B, %Y')`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#%%%%%%%%%%%%%%%%%%%%%%%%%%% LOAD LIBRARIES %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
suppressMessages(library(tidyverse))
suppressMessages(library(broom))
suppressMessages(library(data.table))
suppressMessages(library(e1071))
suppressMessages(library(glmnet))
suppressMessages(library(doMC))
suppressMessages(library(survminer))
suppressMessages(library(survival))
#suppressMessages()
options(expressions = 5e5)


#------------------------ Cluster
cores <- detectCores()
registerDoMC(cores = cores-1)

#------------------------ Trace progress for E-NET
glmnet.control(itrace = 1)
```


```{r read_data}
#%%%%%%%%%%%%%%%%%%%%%%%%%%% READ DATA %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
dat <- fread(file = "../../Project_data/20221201_Full_Dataset.csv")

dat1 <- dat ## make a copy
#dat<- dat1 ## resetting
dat <- dat  %>%
          rename(study_source = study,
                 met_location = Met_location,
                 tissue_source = tissue) %>%
          mutate(study_source = as.factor(study_source),
                     tissue_source = as.factor(tissue_source),
                     met_location = as.factor(met_location),
                     has_met = as.factor(ifelse(met_location == "None", "No", "Yes"))
                     )

```


```{r data_wrangling}
#%%%%%%%%%%%%%%%%%%%%%%%%%%%% DATA WRANGLING %%%%%%%%%%%%%%%%%%%%%%
#slice_dat <- dat[1:20, 1:10]
#view(slice_dat)
#slice_dat %>% str

#dat %>% filter(is.na(met_location)) %>% dim

#--------------------------------- Pre-Processing ----------------------
# Set aside variables not yet needed
cancer_dat <- dat %>%
               filter(!is.na(tissue_source) & !is.na(met_location)) %>%
               dplyr::select(-c(V1, study_source)) #%>%
              #mutate(id = row_number(), .before = names(.)[1])
grp_by_tissue     <- cancer_dat %>%
                      group_by(tissue_source) %>%
                      summarise(n = n()) %>%
                      mutate(prop = n / sum(n))
grp_by_metastasis <- cancer_dat %>%
                      group_by(has_met) %>%
                      summarise(n = n())%>%
                      mutate(prop = n / sum(n))
#xx <- makeX(cancer_dat[, 1:10000], na.impute = TRUE, sparse = TRUE)
               


# Create training (70%) and test (30%) sets for the data weighted by tissue source.
# Use set.seed for reproducibility
set.seed(123)
split <- rsample::initial_split(cancer_dat, prop = .7, strata = "tissue_source")
train <- rsample::training(split)
test  <- rsample::testing(split)

# Create & standardize feature sets based on training parameters
# training features
train_x <- train %>% 
            dplyr::select(-c(tissue_source, met_location, has_met)) 
#train_x[is.na(train_x)] <- 0
# train_x <- train_x %>%
#            mutate_if(is.character,as.numeric)
mean    <- colMeans(train_x)
std     <- apply(train_x, 2, sd)
train_x <- scale(train_x, center = mean, scale = std)
train_y <- train %>% .[["tissue_source"]]

# testing features
test_x <- test %>% 
          dplyr::select(-c(tissue_source, met_location, has_met))
#test_x[is.na(test_x)] <- 0
test_x <- scale(test_x, center = mean, scale = std)
test_y <- test %>% .[["tissue_source"]]


# helper function to filter out low variance genes
uvar <- function(x, means = FALSE) {
  # if means = TRUE, the means and variances are returned, 
  # otherwise just the variances
  m <- colMeans(x)
  n <- nrow(x)
  x <- x - outer(rep(1,n),m)
  v <- colSums(x^2) / (n - 1)
  if (means) list(mean = m, var = v) else v
}

vfilter <- function(q = 0.3, ...) {
  function(x,...) {
    v <- uvar(x)
    which(v < quantile(v, q, na.rm = TRUE))
  }
}


#-------------------------------- MISSINGNESS
# response_nas <- filter(dat, is.na(tissue_source) | is.na(met_location))
# nas    <- sapply(train_x, function(x) sum(is.na(x)))
# na_col <- apply(train_x, 2, function(x) anyNA(x))
# na_col_id <- which(na_col)
# sum(nas)
# nas
# str(train_x)
```


```{r EDA}
#%%%%%%%%%%%%%%%%%%%%%%%%%%%% EDA %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```


```{r modeling_1, cache=TRUE}
#%%%%%%%%%%%%%%%%%%%%%%%%%%% MODEL 1 (E-NET) %%%%%%%%%%%%%%%%%%%%%%
foldid <- sample(rep(1:10, length.out = length(train_y)))

#------------------- search across a range of alphas
tuning_grid <- tibble::tibble(
  alpha      = seq(0, 1, by = .1),
  mse_min    = NA,
  mse_1se    = NA,
  lambda_min = NA,
  lambda_1se = NA
)


for(i in seq_along(tuning_grid$alpha)) {
  
  # fit CV model for each alpha value
  cvfit.filt1 <- cv.glmnet(x = train_x,
                         y = train_y,
                         family = "multinomial",
                         foldid = foldid, 
                         standardize = FALSE,
                         parallel = TRUE,
                         alpha = tuning_grid$alpha[i]
                         )
  
  # extract MSE and lambda values
  tuning_grid$mse_min[i]    <- cvfit.filt1$cvm[cvfit.filt1$lambda == cvfit.filt1$lambda.min]
  tuning_grid$mse_1se[i]    <- cvfit.filt1$cvm[cvfit.filt1$lambda == cvfit.filt1$lambda.1se]
  tuning_grid$lambda_min[i] <- cvfit.filt1$lambda.min
  tuning_grid$lambda_1se[i] <- cvfit.filt1$lambda.1se
}
```


```{r compare, cache=TRUE}
#tuning_grid
tuning_grid %>%
  mutate(se = mse_1se - mse_min) %>%
  ggplot(aes(alpha, mse_min)) +
  geom_line(size = 2) +
  geom_ribbon(aes(ymax = mse_min + se, ymin = mse_min - se), alpha = .25) +
  ggtitle("") +
  labs(x = expression(alpha), y = "minimum deviance")+
  scale_x_continuous(breaks=seq(0,1,0.1)) +
  theme_classic()
```

```{r best_model_1}

#-------------------- Final Model 1
cvfit.filt1 <- cv.glmnet(x = train_x,
                         y = train_y,
                         family = "multinomial",
                         foldid = foldid,
                         standardize = FALSE,
                         parallel = TRUE,
                         alpha = 0.4
                         )


#---------------------- Performance
assess.glmnet(cvfit.filt1, newx = test_x, newy = test_y)$class

confusion.glmnet(cvfit.filt1, newx = test_x, newy = test_y)%>%
  xtable::xtable(align = c(rep("c", 9)),
                 label = "", caption = "")
```

```{r predict, cache=TRUE}
#-------------------- Prediction
test_y_hat  <- predict(cvfit.filt1, newx = test_x, type = "class", s = "lambda.min")
train_y_hat <- predict(cvfit.filt1, newx = train_x, type = "class", s = "lambda.min")

#-------------------- Top Influential Variables
# coef(cvfit.filt1, s = "lambda.1se")$Breast %>%
#   tidy() %>%
#   filter(row != "(Intercept)") %>%
#   top_n(25, wt = abs(value)) %>%
#   ggplot(aes(value, reorder(row, value))) +
#   geom_point() +
#   ggtitle("Top 25 influential variables") +
#   xlab("Coefficient") +
#   ylab(NULL)
```



```{r modeling_2}
#%%%%%%%%%%%%%%%%%%%%%%%%%%% MODEL 2 (E-NET) %%%%%%%%%%%%%%%%%%%%%%

#--------------------- Pipeline for train-test data for metastasis
train_x2 <- makeX(data.frame(tissue_source = train_y_hat)) %>%
                      bind_cols(train_x)%>%
                      data.matrix()
train_x2_names <- colnames(train_x2)  

train_y2 <- train %>% .[["has_met"]]


test_x2 <- makeX(data.frame(tissue_source = test_y_hat)) %>%
                      bind_cols(test_x) %>%
                      data.matrix()
test_y2 <- test %>% .[["has_met"]]



foldid <- sample(rep(1:10, length.out = length(train_y2))) 

#-------------------- Model 1
cvfit.mod_set2 <- cv.glmnet(x = train_x2,
                            y = train_y2,
                            family = "binomial",
                            foldid = foldid, 
                            standardize = FALSE,
                            parallel = TRUE,
                            alpha = 1
                         )

#---------------------- Performance
assess.glmnet(cvfit.mod_set2, newx = test_x2, newy = test_y2)$class

confusion.glmnet(cvfit.mod_set2, newx = test_x2, newy = test_y2) %>%
  xtable::xtable(align = c("l", "c", "c"),
                 label = "", caption = "")

#-------------------- Prediction
test_y_hat_2 <- predict(cvfit.mod_set2, newx = test_x2, type = "class", s = "lambda.min")
```



```{r grand_err}
#%%%%%%%%%%%%%%%%%%%%%%%%%%% GRAND ERROR %%%%%%%%%%%%%%%%%%%%%%%%%%%%%
acc_dat <- data.frame(y1 = test_y,
                      y1_hat = as.factor(test_y_hat),
                      y2 = test_y2,
                      y2_hat = as.factor(test_y_hat_2)) %>%
           mutate(accuracy = factor(case_when(
                                y1 == y1_hat & y1 == y1_hat ~ "accurate",
                                y1 != y1_hat & y1 != y1_hat ~ "inaccurate",
                                TRUE ~ "semi-accurate"))
                  )



plt <- acc_dat %>% 
        count(accuracy = accuracy) %>% 
        mutate(pct = prop.table(n)) %>% 
        ggplot(aes(x = accuracy, y = pct, fill = accuracy, label = scales::percent(pct))) + 
           geom_col(position = 'dodge') + 
           geom_text(position = position_dodge(width = .9),    # move to center of bars
                        vjust = -0.5,    # nudge above top of bar
                         size = 3) + 
       labs(y = "Percent", fill="accuracy") +
       scale_y_continuous(labels = scales::percent) +
       theme_classic()
plt




#-------------------- Top Influential Variables
coef(cvfit.mod_set2, s = "lambda.1se") %>%
  as.matrix() %>%
  as.data.frame() %>%
  rownames_to_column(var = "rowname") %>%
  rename(value = s1) %>%
  filter(rowname != "(Intercept)") %>%
  top_n(25, wt = abs(value)) %>%
  ggplot(aes(value, reorder(rowname, value), color = value > 0)) +
  geom_point() +
  ggtitle("Top 25 influential genes") +
  xlab("Coefficient") +
  ylab(NULL) + theme_bw()
```


```{r survival_modeling}
#%%%%%%%%%%%%%%%%%%%%%%%%%%% SURVIVAL MODELING %%%%%%%%%%%%%%%%%%%%%%
#fit <- survfit(Surv(time, status) ~ met, data = cancer)



# ggsurvplot(
#    fit,                     # survfit object with calculated statistics.
#    data = cancer,           # data used to fit survival curves.
#    risk.table = TRUE,       # show risk table.
#    pval = TRUE,             # show p-value of log-rank test.
#    conf.int = TRUE,         # show confidence intervals for 
#                             # point estimates of survival curves.
#    xlim = c(0,500),         # present narrower X axis, but not affect
#                             # survival estimates.
#    xlab = "Time in days",   # customize X axis label.
#    break.time.by = 100,     # break X axis in time intervals by 500.
#    ggtheme = theme_light(), # customize plot and risk table with a theme.
#  risk.table.y.text.col = T, # colour risk table text annotations.
#   risk.table.y.text = FALSE # show bars instead of names in text annotations
#                             # in legend of risk table
# )
```


















